version: '3.5'
services:
  bend:
    restart: always
    build: .
    container_name: bend
    hostname: bend
    volumes:
      - ./db:/db
    ports:
      - 8080:8080
    networks:
      - default


